### ISSUE TITLE
Feature Request: Ability to Override/Mock out globalLogger in log Package

### ISSUE THREAD

**Issue by cpheps** [newrelic/infra-integrations-sdk#141]
##### Description of the problem

It would be very helpful to be able to mock out/override the global logger in the `log` package. It's not trivial right now to test error or other cases that just log rather than return a certain value.

Having a function in the log package that can set the global logger to a struct that implements the `Logger` interface would be helpful.

Something similar to this:

```
func SetGlobalLogger(logger Logger) {
    globalLogger = logger
}
```

##### Integrations SDK version
 N/A

##### Golang version
N/A

##### OS
N/A

**Comment by jfjoly** [comment]
Closing older issue. Let us know if you still need this.
