### ISSUE TITLE
JMX Package Can Silently Drop Stderr When Command Fails

### ISSUE THREAD

**Issue by jaloren** [newrelic/infra-integrations-sdk#142]
##### Description of the problem

I spent a couple hours on this but due to the package variables (global sadness) and the fine grained locking, I realized I would likely have ended up completely rewriting the package. So instead I'll simply highlight the problem and allow someone to make an incremental change.

The JMX command is run here with cmd.Wait:

https://github.com/newrelic/infra-integrations-sdk/blob/master/jmx/jmx.go#L99

If that fails, it sends on err channel in the goroutine. Open command will not return a non-nil error since that's in a separate goroutine. 

So then a doQuery func is run where it will send a string to os.Pipe, which since its a valid buffered pipe will succeed if the command is in the process of failing (still listening on the pipe) but has not yet exited. So I think there might be race condition.

https://github.com/newrelic/infra-integrations-sdk/blob/master/jmx/jmx.go#L135

So then we have receiveResult func, which has a select. The select is random. So the first case statement could evaluate and then you'll get "got empty result for query" error message so while there is data in stderr pipe its silently dropped.

https://github.com/newrelic/infra-integrations-sdk/blob/master/jmx/jmx.go#L179

##### Integrations SDK version
v2.1 

##### Golang version

go 1.10

##### OS

- Red Hat 7.5

**Comment by varas** [comment]
Hi @jaloren, sorry for the late response. We'll release a fix for this issue soon.

About the global sadness within `jmx` package, you are def right. We know that it requires a whole rewrite but that's not high priority at the moment. 

cc @cristianciutea

**Comment by varas** [comment]
Released at https://github.com/newrelic/infra-integrations-sdk/releases/tag/v3.5.0
