### ISSUE TITLE
HTTP client can't be configured to accept invalid hostnames

### ISSUE THREAD

**Issue by camdencheek** [newrelic/infra-integrations-sdk#185]
##### Description of the problem

The HTTP client currently does not have many configuration options as far as tolerance of invalid certificates. A few customers have requested the ability to accept certificates that don't match the hostname of the server they are connecting to (https://github.com/newrelic/nri-elasticsearch/issues/45). 

##### Integrations SDK version

- [ ] dev
- [ ] 1.0
- [ ] ...

##### Golang version

- [x] All of them
- [ ] 1.8
- [ ] 1.7
- [ ] ...

##### OS

- [x] All of them
- [ ] Amazon Linux, all versions
- [ ] CentOS, version 6 or higher
- [ ] Debian, version 7 ("Wheezy") or higher
- [ ] Red Hat Enterprise Linux (RHEL), version 6 or higher
- [ ] Ubuntu, versions 12.04, 14.04, and 16.04 (LTS  versions)
- [ ] Windows Server, 2008 and 2012 and their service packs

**Comment by mariomac** [comment]
Thanks for the request. We are including this task to our backlog.

**Comment by laf-rge** [comment]
I believe https://github.com/golang/go/issues/21971#issuecomment-332693931 is what we want. I need this as well we have cloud ES clusters with a valid certificate but ephemeral hostnames/IPs that the nri-elasticsearch plugin can not connect to because the hostname is not in the certificate.

**Comment by chrisferry** [comment]
Can we get an update on this?  I cannot use the elasticsearch integration because of this issue

**Comment by varas** [comment]
This feature request has been accepted. We're releasing a new SDK version including this.

**Comment by varas** [comment]
This has been released at https://github.com/newrelic/infra-integrations-sdk/releases/tag/v3.6.4
