### ISSUE TITLE
Use jmx.Query example bug

### ISSUE THREAD

**Issue by ccmanito** [newrelic/infra-integrations-sdk#223]
##### Description of the problem

This form is for integrations-sdk bug reports and feature requests only.
This is NOT a help site. Do not ask help questions here.
If you need help, please use [newrelic support?]().

Describe the bug or feature request in detail.
Use example bug ：
error  ”./main.go:14:79: cannot use 5 * time.Second (type time.Duration) as type int in argument to jmx.Query“

A code snippet, screenshot, and small-test help us understand.

Place the appropriate label to the issue: bug, feature, enhancement, ...

##### Integrations SDK version

- [ ] dev
- [ ] 1.0
- [ ] ...

##### Golang version

- [x] All of them
- [ ] 1.8
- [ ] 1.7
- [ ] ...

##### OS

- [x] All of them
- [ ] Amazon Linux, all versions
- [ ] CentOS, version 6 or higher
- [ ] Debian, version 7 ("Wheezy") or higher
- [ ] Red Hat Enterprise Linux (RHEL), version 6 or higher
- [ ] Ubuntu, versions 12.04, 14.04, and 16.04 (LTS  versions)
- [ ] Windows Server, 2008 and 2012 and their service packs

**Comment by varas** [comment]
time.Duration is not accepted by Query func, timeout should be provided as integer representing the amount of millis `Query(objectPattern string, timeoutMillis int)`
