### ISSUE TITLE
Update metrics API endpoint for FedRAMP - Infra agent

### ISSUE THREAD

**Issue by orion-fra** [newrelic/infra-integrations-sdk#230]
For FedRAMP customers there is a special gov-infra-api.newrelic.com domain.

In order to move Infra to dimensional metrics in a FedRAMP approved way, we need to make sure the dimensional metrics capability is following the same approach: going straight to CHI and avoid CloudFlare and cells.

**Comment by josemore** [comment]
This has been implemented in the agent and [documented](https://docs.newrelic.com/docs/security/security-privacy/compliance/fedramp-compliant-endpoints).
