### ISSUE TITLE
Update metrics API endpoint for FedRAMP - POMI

### ISSUE THREAD

**Issue by orion-fra** [newrelic/infra-integrations-sdk#232]
Currently dimensional metrics are going through CloudFlare and are routed to a Cell. Both of these mechanisms are not FedRAMP approved. For FedRAMP customers there is a special gov-infra-api.newrelic.com domain that doesn't use CloudFlare or cells.

In order to move Infra to dimensional metrics in a FedRAMP approved way, we need to make sure the dimensional metrics capability is following the same approach: going straight to CHI and avoid CloudFlare and cells.

Instead of using the current domain: metric-api.newrelic.com, we will be using infra-api.newrelic.com. For POMI we need to update the default url.

**Comment by carlosroman** [comment]
The SDK does not have a concept of endpoints so does not understand what _ FedRAMP_ is. This is used to communicate with the agent and so the changes are most likely needed there (if there are any to be made).
