### ISSUE TITLE
Merge telemetry-sdk changes (cumulative-rate and rate)

### ISSUE THREAD

**Issue by orion-fra** [newrelic/infra-integrations-sdk#234]
PR:
https://github.com/newrelic/newrelic-telemetry-sdk-go/pull/13

It has been reviewed by them. We need to tackle the feedback and get the changes merged.

After this is done, we'll need to replace the forked version with the official one.

**Comment by carlosroman** [comment]
Both `cumulative-rate` and `rate` have been moved into the [infra agent](https://github.com/newrelic/infrastructure-agentl).
