### ISSUE TITLE
Setters and document the "common" attribute

### ISSUE THREAD

**Issue by gsanchezgavier** [newrelic/infra-integrations-sdk#250]
There is a `common` [field ](https://github.com/newrelic/infra-integrations-sdk/blob/master/integration/entity.go#L15)in the payload that could be used for attributes shared by entities and metrics. This is not documented and also there are no methods instrumented to add this values. 

Would be good to document this attribute behavior with some examples, and also add the setters to this.

**Comment by varas** [comment]
Released at https://github.com/newrelic/infra-integrations-sdk/releases/tag/v4.1.0
