### ISSUE TITLE
Downloading sdkv4

### ISSUE THREAD

**Issue by paologallinaharbur** [newrelic/infra-integrations-sdk#251]
SDKv4 has been released but we had issues importing it

```
$go get github.com/newrelic/infra-integrations-sdk/v4@v4.0.0
go get github.com/newrelic/infra-integrations-sdk/v4@v4.0.0: github.com/newrelic/infra-integrations-sdk@v4.0.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v4

$go get github.com/newrelic/infra-integrations-sdk@v4.0.0
go get github.com/newrelic/infra-integrations-sdk@v4.0.0: github.com/newrelic/infra-integrations-sdk@v4.0.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v4
```

If I run simply `$go get github.com/newrelic/infra-integrations-sdk` I get version:
`github.com/newrelic/infra-integrations-sdk v3.6.5+incompatible // indirect`

Should we add in the go.mod the version of the package? 
something like [this](https://github.com/google/go-github/blob/2e3e74fa920e7d6278b7a9737ab5c8b7b1480294/go.mod#L1) 

https://github.com/golang/go/issues/35732#issuecomment-584319096

**Comment by carlosroman** [comment]
So we did something bad and delete the old V4 tag as realised that the way `go mod` was implemented was in correct. We recreated the tag with a fix added to it. You now have to use `go get github.com/newrelic/infra-integrations-sdk/v4`.

**Comment by carlosroman** [comment]
But yes, fix was to add the version to the package as you can see from the PR #252.

**Comment by paologallinaharbur** [comment]
Awesome thanks, we can close the issue I believe

**Comment by paologallinaharbur** [comment]
$ go get github.com/newrelic/infra-integrations-sdk/v4
go: github.com/newrelic/infra-integrations-sdk/v4 upgrade => v4.0.0
